name: RPG-Paper
version: '${project.version}'
main: com.raaaaming.rpgpaper.Main
api-version: 1.16
authors: [ Raaaaming ]
description: This Plugin is RPG Plugin

commands:
  rpg:
    description: rpg command
  stat:
    aliases:
      - stat
      - 스탯
      - 스텟
      - tmxpt
      - tmxot
    description: stat command